# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventory.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finventory.proto\x12\tinventory\"\x9d\x01\n\x10InventoryRequest\x12\x0f\n\x07item_id\x18\x01 \x01(\t\x12\x15\n\rcurrent_stock\x18\x02 \x01(\x05\x12\x18\n\x10predicted_demand\x18\x03 \x01(\x05\x12\x15\n\rreorder_level\x18\x04 \x01(\x05\x12\x14\n\x0csafety_stock\x18\x05 \x01(\x05\x12\x1a\n\x12supplier_lead_time\x18\x06 \x01(\x05\"C\n\x15InventoryBatchRequest\x12*\n\x05items\x18\x01 \x03(\x0b\x32\x1b.inventory.InventoryRequest\"\xa6\x01\n\x11InventoryResponse\x12\x0f\n\x07item_id\x18\x01 \x01(\t\x12\x18\n\x10reorder_quantity\x18\x02 \x01(\x05\x12I\n\x1binventory_adjustment_action\x18\x03 \x01(\x0e\x32$.inventory.InventoryAdjustmentAction\x12\x1b\n\x13\x65xplanation_message\x18\x04 \x01(\t*U\n\x19InventoryAdjustmentAction\x12\r\n\tNO_ACTION\x10\x00\x12\x0c\n\x08SCALE_UP\x10\x01\x12\x0e\n\nSCALE_DOWN\x10\x02\x12\x0b\n\x07REORDER\x10\x03\x32\xc4\x01\n\x15InventoryOptimization\x12N\n\x11OptimizeInventory\x12\x1b.inventory.InventoryRequest\x1a\x1c.inventory.InventoryResponse\x12[\n\x17OptimizeInventoryStream\x12 .inventory.InventoryBatchRequest\x1a\x1c.inventory.InventoryResponse0\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INVENTORYADJUSTMENTACTION._serialized_start=428
  _INVENTORYADJUSTMENTACTION._serialized_end=513
  _INVENTORYREQUEST._serialized_start=31
  _INVENTORYREQUEST._serialized_end=188
  _INVENTORYBATCHREQUEST._serialized_start=190
  _INVENTORYBATCHREQUEST._serialized_end=257
  _INVENTORYRESPONSE._serialized_start=260
  _INVENTORYRESPONSE._serialized_end=426
  _INVENTORYOPTIMIZATION._serialized_start=516
  _INVENTORYOPTIMIZATION._serialized_end=712
# @@protoc_insertion_point(module_scope)
