# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: demand_forecast.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x64\x65mand_forecast.proto\x12\x08\x66orecast\"s\n\x15\x44\x65mandForecastRequest\x12\x0f\n\x07item_id\x18\x01 \x01(\t\x12\x19\n\x11historical_demand\x18\x02 \x03(\x05\x12\x18\n\x10\x66orecast_horizon\x18\x03 \x01(\x05\x12\x14\n\x0cwarehouse_id\x18\x04 \x01(\t\"z\n\x16\x44\x65mandForecastResponse\x12\x0f\n\x07item_id\x18\x01 \x01(\t\x12\x18\n\x10predicted_demand\x18\x02 \x01(\x05\x12\x1b\n\x13\x66orecast_confidence\x18\x03 \x01(\x01\x12\x18\n\x10\x66orecast_horizon\x18\x04 \x01(\x05\x32\x64\n\x0e\x44\x65mandForecast\x12R\n\rPredictDemand\x12\x1f.forecast.DemandForecastRequest\x1a .forecast.DemandForecastResponseB*\n\x11\x63om.iscf.forecastB\x13\x44\x65mandForecastProtoP\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'demand_forecast_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021com.iscf.forecastB\023DemandForecastProtoP\001'
  _DEMANDFORECASTREQUEST._serialized_start=35
  _DEMANDFORECASTREQUEST._serialized_end=150
  _DEMANDFORECASTRESPONSE._serialized_start=152
  _DEMANDFORECASTRESPONSE._serialized_end=274
  _DEMANDFORECAST._serialized_start=276
  _DEMANDFORECAST._serialized_end=376
# @@protoc_insertion_point(module_scope)
