# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import demand_forecast_pb2 as demand__forecast__pb2


class DemandForecastStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PredictDemand = channel.unary_unary(
                '/forecast.DemandForecast/PredictDemand',
                request_serializer=demand__forecast__pb2.DemandForecastRequest.SerializeToString,
                response_deserializer=demand__forecast__pb2.DemandForecastResponse.FromString,
                )


class DemandForecastServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PredictDemand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DemandForecastServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PredictDemand': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictDemand,
                    request_deserializer=demand__forecast__pb2.DemandForecastRequest.FromString,
                    response_serializer=demand__forecast__pb2.DemandForecastResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'forecast.DemandForecast', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DemandForecast(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PredictDemand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/forecast.DemandForecast/PredictDemand',
            demand__forecast__pb2.DemandForecastRequest.SerializeToString,
            demand__forecast__pb2.DemandForecastResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
